export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  NOT_FOUND: "NOT_FOUND",
  STOCK_SHORTAGE: "STOCK_SHORTAGE",
  STATUS_CONFLICT: "STATUS_CONFLICT",
  REASON_REQUIRED: "REASON_REQUIRED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  NETWORK_ERROR: "NETWORK_ERROR"
} as const;
