export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  NOT_FOUND: "NOT_FOUND",
  REASON_REQUIRED: "REASON_REQUIRED",
  APPROVAL_STATE_INVALID: "APPROVAL_STATE_INVALID",
  TEAM_SCOPE_DENIED: "TEAM_SCOPE_DENIED",
  STOCK_SHORTAGE: "STOCK_SHORTAGE"
} as const;
